-- SugarCRM
REVOKE CONNECT ON DATABASE FROM USER sugarcrm;

GRANT CONNECT ON DATABASE TO USER sugarcrm;

COMMIT;

-- db2user
REVOKE CONNECT ON DATABASE FROM USER db2user;

GRANT CONNECT ON DATABASE TO USER db2user;

COMMIT;