-- SUGARCRM
DROP USER sugarcrm CASCADE;

CREATE USER sugarcrm IDENTIFIED BY sugarcrm ;

GRANT RESOURCE,CONNECT TO sugarcrm ;

ALTER USER sugarcrm QUOTA UNLIMITED ON USERS;

-- DWHSTAGE
DROP USER dwhstage CASCADE;

CREATE USER dwhstage IDENTIFIED BY dwhstage ;

GRANT RESOURCE,CONNECT TO dwhstage ;

ALTER USER dwhstage QUOTA UNLIMITED ON USERS;